function y = Comb(x)
%COMB Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 14-Aug-2021 00:41:22

persistent Hd;

if isempty(Hd)
    
    % IIR Comb Notching filter designed using the IIRCOMB function.
    
    % All frequency values are in Hz.
    Fs = 44100;  % Sampling Frequency
    
    N     = 147;  % Order
    BW    = 2;    % Bandwidth
    Apass = 20;   % Bandwidth Attenuation
    
    [b, a] = iircomb(N, BW/(Fs/2), Apass);Hd = dsp.IIRFilter( ...
        'Structure', 'Direct form II', ...
        'Numerator', b, ...
        'Denominator', a);
end

y = step(Hd,double(x));


% [EOF]
